### PR TITLE
Scikit Learn wrapper

### PR DESCRIPTION
**Pull request by anivegesana**
As promised, added the scikit learn wrapper.

---
What was the next version, 0.0.10? Do you need help building the wheels? I would suggest using a tool like this: https://cibuildwheel.readthedocs.io/en/stable/

Building on a CI would save the hassle of verifying that the wheels work on all machines of the given OS. For example, running auditwheel on my Linux wheel shows problems that might arise when using the wheel on older versions of Linux:
```
dbscan-0.0.9-cp38-abi3-linux_x86_64.whl is consistent with the
following platform tag: "manylinux_2_31_x86_64".

The wheel references external versioned symbols in these
system-provided shared libraries: libgcc_s.so.1 with versions
{'GCC_3.0'}, libc.so.6 with versions {'GLIBC_2.4', 'GLIBC_2.14',
'GLIBC_2.2.5'}, libm.so.6 with versions {'GLIBC_2.29', 'GLIBC_2.2.5'},
libstdc++.so.6 with versions {'GLIBCXX_3.4.21', 'GLIBCXX_3.4.17',
'GLIBCXX_3.4.9', 'GLIBCXX_3.4.11', 'CXXABI_1.3.9', 'CXXABI_1.3',
'GLIBCXX_3.4.19', 'CXXABI_1.3.11', 'GLIBCXX_3.4.22', 'GLIBCXX_3.4'},
libpthread.so.0 with versions {'GLIBC_2.2.5'}

This constrains the platform tag to "manylinux_2_31_x86_64". In order
to achieve a more compatible tag, you would need to recompile a new
wheel from source on a system with earlier versions of these
libraries, such as a recent manylinux image.
```
Compiling in a containerized environment solves this by using the oldest possible version of GCC that still works with Python to compile the program and ensure that the wheel will work on every machine that supports Python on that given OS. Plus, you can compile wheels for machines that you don't physically own.

### CODE REVIEW

**Comment by wangyiqiu** [comment]
Hi @anivegesana 
I think it's a great idea to integrate the project with CI and build the wheels automatically. And yes the next version is 0.0.10. While I look into adding CI to the project, let me know if you have suggestions or relevant pointers. And thanks for working on this sklearn wrapper.

**Comment by anivegesana** [comment]
Since this was sitting here for a while, I should probably give an update. pbbs/utils.h is very x86 GCC specific. Because of this, it is not possible to compile the program for Windows or Musl or on the ARM architecture. In order to get it to work across multiple platforms, a more general version using the C++ [atomic](https://en.cppreference.com/w/cpp/atomic/atomic_compare_exchange) header (or the C stdatomic.h equivalent) needs to be written. I do not have any experience in parallel programming, but it seems like `atomic_compare_exchange_weak` is equivalent to some of the functions in pbbs/utils.h.

Wheels are able to be compiled via CI for Mac and Linux on x86 GCC. Here is the run: [link](https://github.com/anivegesana/dbscan-python/actions/runs/3519626421). Is Windows or ARM something that you are planning on looking at in the near future or should we just settle for this smaller subset of OSes and architectures for now for 0.0.10?

**Comment by wangyiqiu** [comment]
Hi @anivegesana , thanks for setting up the Github CI and cibuildwheel! I verified one of the artifacts and it worked on my Ubuntu.

Yes I think it may be possible to swap out the x86 gcc specific instructions to increase compatibility for Windows, Musl, and ARM architecture. FYI that the parallel utilities of pbbs has been updated [here](https://github.com/cmuparlay/parlaylib/blob/master/include/parlay/utilities.h), which I believe after some adaptation, can enable us to get rid of the x86 gcc specific instructions using C++ atomic header. I will look into it and will try to update it in two weeks. For now, I am ok with supporting a smaller set of OSes and architecture for 0.0.10.

**Comment by anivegesana** [comment]
Awesome! I can see that they fixed it and all you need to do is make the changes to the DBSCAN code so that `atomic` is used instead of direct pointers.

I didn't add the test cases to the CI yet, to save time during debugging. (Each build seems to take 15 minutes, so the extra build time didn't seem worth it yet.) I will probably add the test for Linux since the underlying PPBS library should handle the parallelization and make it work across all OSes. For the releases, it would be useful to run all tests.

**Comment by anivegesana** [comment]
To get the version numbers for development builds, can you run the following commands?
```sh
git tag v0.0.7 47634af1638b5111213c724c3f044595f4975271
git tag v0.0.8 242ffd709213c2efda304fc826ad7eead8c0baa7
git tag v0.0.9 304867b9dbc4abd4a6d1efa55f3bd7a3d6004ba5
git push origin v0.0.7
git push origin v0.0.8
git push origin v0.0.9
```
This will create tags that can be used by setuptools_scm to automatically version builds. To automatically build wheels for a release, all you need to do is create a tag in the same way as above (except the commit numbers are not required) and push the tag and the commit containing the release with the following commands:
```sh
# Do not run these until you want to make a release
git tag v0.0.10
git push --atomic origin v0.0.10 master 
```
Then, the CI will build the wheels. Optionally, you can add your `pypi_password` to https://github.com/wangyiqiu/dbscan-python/settings/secrets/actions to automatically upload the wheels to PyPI, but I would hold off on that for this version or test it with [TestPyPI](https://test.pypi.org/) so that we can make sure that everything is working without hickups.

**Comment by anivegesana** [comment]
@wangyiqiu You can see the build errors by clicking on the red X and clicking on details. Then, the "building wheel" section of the logs should have the error that caused the build fail.

I think that PyPy will probably not be used by most people. I think it is OK to turn it off. I am still working on getting the build process to save time when compiling the executable, test cases, and Python module by not recompiling capi.cpp, but that seems to be more difficult than I anticipated. This change is probably not going to effect anything until you get it to compile on other architectures, so we can worry about it later.
https://github.com/anivegesana/dbscan-python/blob/sklearn-wrapper/pyproject.toml#L46

**Comment by wangyiqiu** [comment]
Hi @anivegesana I think that's a good idea, thanks for working on this!

I created a new branch called 0.0.10-dev, where I am fixing the Windows build, and adding test cases to the CI. So far it seems to be working, though yes it is quite slow.
I guess for 0.0.10 we can include ubuntu, mac and windows as discussed above.
Let me know if you have any suggestions.

I will update the repo with a pypi api key soon, after everything is done we can tag the commit for a new release.

**Comment by anivegesana** [comment]
Sounds good. Let me know when you finish getting Windows to work. Then, we can test it on ARM. Most likely, it will work if it works on Windows and Linux. The lines that you need to change to turn on ARM builds are in the same `pyproject.toml` file. Unfortunately, they run the builds in small sandboxed VMs so that they can build many projects at the same time, so it will always be extremely slow. I will be looking into seeing if I can make it only build Windows x86 and Linux ARM builds during the non-master branch builds to speed up  debugging, but that change probably won't be useful until the project builds on all possible Python platforms.

**Comment by anivegesana** [comment]
The reason that PyPy builds seem to take so long is because numpy only has wheels for PyPy 3.8 instead of 3.9, the version I was building against in the CI. https://pypi.org/project/numpy/#files

This means that the CI has to build both dbscan and numpy for the PyPy builds. Unlike CPython, PyPy's stable ABI (HPy) is still in alpha and may have breaking changes in the future, so it is not reasonable to distribute HPy wheels and it probably won't be for a couple more years. We could remember to change `pyproject.toml` every time numpy changes their build configuration in order, but it is probably easiest to drop PyPy builds. Users can build the package from source if they want to use PyPy. We could change this for the release builds, but I haven't figured that out yet. This shouldn't effect too many people, but it is something I will look into later.

You seem to have gotten Windows builds to work. I got ARM wheels to build on Windows and am getting musl and ARM to work on Linux. I will open a PR when that is done.

**Comment by wangyiqiu** [comment]
Hi @anivegesana I think the repository is ready for PyPI v0.0.10 by tagging the most recent commit in master branch. Any additional suggestions before I do so?

**Comment by anivegesana** [comment]
With regards to saying that you want to implement an alternate implementation in the future for a large number of dimensions, maybe we should remove these two attributes from the Python module:

https://github.com/wangyiqiu/dbscan-python/blob/master/src/dbscanmodule.cpp#L122-L123

In addition, maybe this guarantee shouldn't be as strong and maybe we should remove it, but that is your call:

https://github.com/wangyiqiu/dbscan-python/blob/master/README.md?plain=1#L151

Besides those two potential changes, I think it is ready to publish to PyPI.

**Comment by wangyiqiu** [comment]
@anivegesana 
I see. The higher dimensional DBSCAN I mentioned probably requires slightly more planning, so let's keep these macros for setting the min/max dimensionality for now.
For the latter issue you mentioned, let's keep the "dbscan/algo.h" and "dbscan/capi.h" as the high dimensional implementation can have a different API, or it may even be purely in Python if we decide to fall back to other implementations like the one in sklearn.

**Comment by anivegesana** [comment]
I think I may have not been clear in my first question. The question was whether or not we should expose the macros in the Python module and allow users to access them in case if they wanted to pick, say sklearn, in the case that this library wasn't compiled for that particular number of dimensions. From your answer, however, I believe the answer is still keep them.

**Pull request merged**
