### PR TITLE
Major changes in the Python packaging of the library

### LINKED ISSUE #2: pypi module not working
hello, the compiled module works like a charm but the module from pypi fails to load the DBSCAN method with error:
cannot import name 'DBSCAN' from 'dbscan' (unknown location)

awesome work btw

### LINKED ISSUE #5: Cannot import in Conda environment
In my conda environment:
`>>> import dbscan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zpyang/anaconda3/envs/visnet/lib/python3.9/site-packages/dbscan/__init__.py", line 22, in <module>
    from dbscan.DBSCAN import DBSCAN
ModuleNotFoundError: No module named 'dbscan.DBSCAN'
`
but it is successfully imported while outside the conda environment. Not sure why that's the case.

### PR DESCRIPTION
**Pull request by anivegesana**
I have changed a lot of stuff in the Python packaging to allow for it to work across many OS's and Python and numpy versions. Here is a list of the major 

- [x] Add a pyproject.toml to add setup-time dependencies
- [x] Get rid of the Caller class and just make it a function (breaks depending packages that use the source of this package directly)
- [x] Move core DBSCAN wrapper functionality in Caller into a `src/dbscan/algo.h` file that can be included and templated to create faster compilation in C++ programs if the number of dimensions is known at compile time
- [x] Change Caller.cpp to return an int for errors instead of the labels, so that I can avoid IO during error and use the Python error handling
- [x] Replace Cython code with a C++ wrapper written bare metal so that I can leverage the Python limited C API to allow many Python versions to use the same binary (like OpenCV does)
- [x] Enforce using the oldest possible numpy version during compile-time to make sure that downgrading numpy will not break the binary

I have tested my changes on Ubuntu and MacOS. Here are the wheels: https://gist.github.com/anivegesana/8c23b7356e0f93dfe1ec79ceea33c100

They should also be compiled for all of the OSes that [numpy supports](https://pypi.org/project/numpy/#files), but compiling for many different versions of Python isn't necessary. You only need different binaries for each OS. You might also want to recompile for the two OSes I compiled for using a CI or Docker container, in case if I missed anything related to system dependencies. I don't think I did, but it is good to check.

Yank your old releases so PIP doesn't get confused and install the older Linux version on computers that can't run it. And add a source distribution when you publish to PyPI so that the package can be built from source on the machines that you didn't compile for.

---

If these changes are too breaking, you might want to avoid pulling them, but I believe that these changes will increase the usability of this package and each major change in the packaging is in service of making it more portable and usable.

This is the fastest DBSCAN library for Python I was able to find. Thank you for your great work in creating this library and I hope it gains traction.

Fixes #2, fixes #5

### CODE REVIEW

**Comment by anivegesana** [comment]
I also have a version without the breaking change of removing `Wrapper::Caller`, but I would definitely recommend using `dbscan/algo.h`, since it is much more flexible and saves significantly on compile time if the number of dimensions are known at compile time.

**Comment by wangyiqiu** [comment]
Hi @anivegesana, thanks a lot for your nice work. I've tested your changes and I believe they work well. I will update the changes to PyPI soon.

**Comment by anivegesana** [comment]
I think I should push the changes that add back the Caller class so it doesn't break people's code (the people who use the C++ caller directly.) I probably should have converted it back to a draft.

Was the Caller class a documented feature that you expected others to use direct? I guess I will open a new PR that adds it back. I think creating a includes directory with the public facing header files would be incredibly useful.

**Comment by anivegesana** [comment]
@wangyiqiu I was also looking into creating a sklearn compatible wrapper along with the low level C API function call that already exists:
```py
import sklearn.base
import sklearn.cluster

class sklDBSCAN(sklearn.base.BaseEstimator):
    __slots__ = ('core_sample_indices_', 'components_', 'labels_', 'n_features_in_', 'feature_names_in_')
    def __init__(self, eps=0.5, *, min_samples=5, metric='euclidean', metric_params=None, algorithm='auto', leaf_size=30, p=None, n_jobs=None):
        if metric != 'euclidean': raise NotImplementedError('Only euclidean metric supported')
        if algorithm not in ('auto', 'kd_tree'): raise NotImplementedError('Only kd tree is supported')
        if leaf_size != 30: raise NotImplementedError('Leaf size not supported')
        if p not in (None, 2): raise NotImplementedError('Only Euclidean distance supported')
        if n_jobs is not None: raise NotImplementedError('Parallelization is done automatically')
    def fit_predict(self, X, y=None, sample_weight=None):
        if sample_weight is not None: raise NotImplementedError('sample_weight not supported')
        labels, core_samples = DBSCAN(X, self.eps, min_samples=self.min_samples)
        self.core_sample_indices_ = core_sample_indices = np.nonzero(core_samples)[0]
        self.components_ = X[core_sample_indices]
        self.labels_ = labels
        self.n_features_in_ = X.shape[1]
        return labels
    def fit(self, X, y=None, sample_weight=None):
        self.fit_predict(X, y=y, sample_weight=sample_weight)
        return self

sklDBSCAN.__module__ = 'dbscan'
sklDBSCAN.__doc__ = \
"""A faster version of DBSCAN (with more limited functionality than sklearn's
version). sklearn's documentation is below.

""" + sklearn.cluster.DBSCAN.__doc__
```
That is totally untested, but it might be something worthwhile to add before pushing out the release.

**Pull request merged**
